apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-claim
  labels:
    app: influxdb
spec:
  storageClassName: influxdb-storage
  selector:
    matchLabels:
      name: influxdb-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:my
        imagePullPolicy: Never
        volumeMounts:
        - name: influxdb-storage
          mountPath: /var/lib/influxdb
        - name: dockersock
          mountPath: /var/run/docker.sock
      volumes:
      - name: influxdb-storage
        persistentVolumeClaim:
          claimName: influxdb-claim
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

---

apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  type: ClusterIP
  ports:
  - port: 8086
  selector:
    app: influxdb
