apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage
  labels:
    type: local
    name: mysql-storage
spec:
  storageClassName: mysql-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    type: DirectoryOrCreate
    path: /var/lib/mysql

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ftps-storage
  labels:
    type: local
    name: ftps-storage
spec:
  storageClassName: ftps-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /home/usr

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-storage
  labels:
    type: local
    name: influxdb-storage
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: influxdb-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    type: DirectoryOrCreate
    path: /var/lib/influxdb
